# Generated by Django 4.2.7 on 2023-11-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("GCI", "Collection Information"),
                            ("PSL", "Preparing a staff list"),
                            ("AR", "Assessing Risk"),
                            ("OCP", "Opening clossing Procedurse"),
                            ("DSP", "Determining Salvage Priorities"),
                            ("PMC", "Preventive Maintenace Check List"),
                            ("IAI", "Collection Insurance and Acccounting Information"),
                            (
                                "FPP",
                                "Facilitaiting Information and Preparing Floor Plans",
                            ),
                            ("CIE", "collection Information Local Emergency"),
                            ("GIS", "Gathering Internal Supplies"),
                            (
                                "DEP",
                                "Devising Emergency Response and Evacuation Procedures",
                            ),
                            ("IPC", "Identifying Potential Command center"),
                            ("PEC", "Preparing Emergency Call List"),
                            ("IPT", "Identifying Potential Volunteers"),
                            ("CST", "Coordinating Staff Training"),
                            ("CSD", "Coordinating Staff Distribution"),
                            ("PCK", "Preparing communication PR Kit"),
                            (
                                "CBI",
                                "Communicating with Bank or Financial Institutions",
                            ),
                            ("MBI", "Maintaining Budy Institutions"),
                            ("IT", "Information Technology"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
