# Generated by Django 4.2.7 on 2023-11-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coop", "0004_housekeepingpestsrisk_personnelrisk_securityrisk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyPMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField()),
                ("other", models.TextField(blank=True, verbose_name="Other Tasks")),
                ("check_emergency_numbers", models.BooleanField(default=False)),
                ("security_system_operable", models.BooleanField(default=False)),
                ("emergency_lights_operable", models.BooleanField(default=False)),
                ("emergency_power_operable", models.BooleanField(default=False)),
                ("alarm_panels_operable", models.BooleanField(default=False)),
                ("keys_accounted_for", models.BooleanField(default=False)),
                ("flashlights_present", models.BooleanField(default=False)),
                ("battery_powered_radio_operable", models.BooleanField(default=False)),
                ("check_pest_traps", models.BooleanField(default=False)),
                ("change_hygrothermograph_chart", models.BooleanField(default=False)),
                ("download_data_logger", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeasonalPMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField()),
                ("other", models.TextField(blank=True, verbose_name="Other Tasks")),
                ("check_caulking", models.BooleanField(default=False)),
                ("clean_gutters", models.BooleanField(default=False)),
                ("check_clean_storm_drains", models.BooleanField(default=False)),
                ("winterize_grounds", models.BooleanField(default=False)),
                ("seasonal_heating_cooling_check", models.BooleanField(default=False)),
                ("spring_planting_maintenance", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyPMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField()),
                ("other", models.TextField(blank=True, verbose_name="Other Tasks")),
                ("clean_restrooms", models.BooleanField(default=False)),
                ("stack_maintenance", models.BooleanField(default=False)),
                ("empty_garbage", models.BooleanField(default=False)),
                ("shovel_snow", models.BooleanField(default=False)),
                ("vacuum_floors", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiannualPMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField()),
                ("other", models.TextField(blank=True, verbose_name="Other Tasks")),
                ("hold_fire_drill", models.BooleanField(default=False)),
                ("inspect_roof_drainage", models.BooleanField(default=False)),
                ("inspect_windows_skylights", models.BooleanField(default=False)),
                ("inspect_building_foundation", models.BooleanField(default=False)),
                ("inspect_fire_detection_system", models.BooleanField(default=False)),
                ("inspect_fire_suppression_system", models.BooleanField(default=False)),
                ("inspect_security_system", models.BooleanField(default=False)),
                ("general_inspection", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnnualPMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_date", models.DateField()),
                ("other", models.TextField(blank=True, verbose_name="Other Tasks")),
                (
                    "check_update_insurance_building_equipment",
                    models.BooleanField(default=False),
                ),
                (
                    "check_update_insurance_collections",
                    models.BooleanField(default=False),
                ),
                (
                    "revise_building_maintenance_budget",
                    models.BooleanField(default=False),
                ),
                ("pump_septic_system", models.BooleanField(default=False)),
                (
                    "arrange_inspection_by_fire_marshal",
                    models.BooleanField(default=False),
                ),
                ("flush_fire_suppression_system", models.BooleanField(default=False)),
                (
                    "arrange_inspection_fire_extinguishers",
                    models.BooleanField(default=False),
                ),
                ("arrange_inspection_elevators", models.BooleanField(default=False)),
                ("inspect_electrical_system", models.BooleanField(default=False)),
                ("inspect_plumbing_system", models.BooleanField(default=False)),
                ("update_service_contracts", models.BooleanField(default=False)),
                ("update_building_plans_drawings", models.BooleanField(default=False)),
                ("inventory_collections", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
