# Generated by Django 4.2.7 on 2023-11-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0006_question_closingstaffschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary",
                    models.CharField(max_length=50, verbose_name="Primary Contact"),
                ),
                (
                    "backup",
                    models.CharField(max_length=50, verbose_name="Backup Contact"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="coop.institution",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qs",
                        to="coop.question",
                    ),
                ),
            ],
        ),
    ]
