# Generated by Django 4.2.7 on 2023-11-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0009_weeklyopening"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitiesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyShutOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shut_off_type",
                    models.CharField(
                        max_length=300, verbose_name="Emergency Shut-Off Type"
                    ),
                ),
                ("procedures", models.TextField(verbose_name="Procedures")),
                (
                    "facility_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_shut_offs",
                        to="coop.facilitiesinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emergency Shut-Offs",
            },
        ),
    ]
