# Generated by Django 4.2.7 on 2023-11-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0010_facilitiesinfo_emergencyshutoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="FireDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fire_alarm_pull_box_number",
                    models.CharField(
                        max_length=255, verbose_name="Fire Alarm Pull Box Number/Name"
                    ),
                ),
                (
                    "fire_alarm_box_location",
                    models.TextField(verbose_name="Location Description"),
                ),
                (
                    "fire_extinguisher_type",
                    models.CharField(
                        choices=[
                            ("ABC", "ABC"),
                            ("Water", "Water"),
                            ("CO2", "CO2"),
                            ("Mist", "Mist"),
                        ],
                        max_length=200,
                        verbose_name="Type of Fire Extinguisher",
                    ),
                ),
                (
                    "fire_location_description",
                    models.TextField(verbose_name="Location Description"),
                ),
                (
                    "last_inspection_date",
                    models.DateField(verbose_name="Date of Last Inspection"),
                ),
                (
                    "heat_detector_type",
                    models.CharField(max_length=300, verbose_name="Type of Detector"),
                ),
                (
                    "monitoring_description",
                    models.TextField(
                        max_length=300,
                        verbose_name="Description of Monitoring Procedures",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fire Detection and Suppression Information",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Location Name")),
            ],
        ),
    ]
