# Generated by Django 4.2.7 on 2023-11-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0011_firedetection_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField()),
                ("date_updated", models.DateField()),
                ("description", models.CharField(max_length=300)),
                (
                    "monitoring_type",
                    models.CharField(max_length=100, verbose_name="Monitoring Type"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heat_detectors", models.CharField(max_length=50)),
                ("smoke_detectors", models.CharField(max_length=50)),
                (
                    "sprinklers",
                    models.CharField(max_length=50, verbose_name="Sprinklers System"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="coop.location",
                    ),
                ),
            ],
            options={
                "ordering": ["location"],
            },
        ),
    ]
