# Generated by Django 4.2.7 on 2023-11-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0012_servicetype_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=150, verbose_name="Contact Person"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Phone Number")),
                (
                    "after_hours_phone",
                    models.CharField(max_length=20, verbose_name="After Hours Phone"),
                ),
                ("pager", models.CharField(max_length=20, verbose_name="Pager")),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
                (
                    "addresses",
                    models.ManyToManyField(
                        related_name="services_companies", to="coop.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GasCompanies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addresses",
                    models.ManyToManyField(
                        related_name="gas_companies_addresses", to="coop.address"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gas_companies",
                        to="coop.services",
                    ),
                ),
            ],
            options={
                "ordering": ["company"],
            },
        ),
    ]
