# Generated by Django 4.2.7 on 2023-11-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0013_services_gascompanies"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_category", models.CharField(max_length=100)),
                ("date_created", models.DateField(blank=True, null=True)),
                ("date_updated", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(
                        max_length=250, verbose_name="Emergency Evacuation Plans"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "after_hours",
                    models.CharField(max_length=20, verbose_name="After Hours Phone"),
                ),
                ("pager", models.CharField(max_length=20, verbose_name="Pager")),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
                (
                    "addresses",
                    models.ManyToManyField(
                        related_name="gas_services_addresses", to="coop.address"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GasCompanies",
        ),
    ]
