# Generated by Django 4.2.7 on 2023-11-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0014_gasservices_delete_gascompanies"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="State Name")),
            ],
        ),
        migrations.CreateModel(
            name="WaterDetectorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Text")),
                (
                    "detector_type",
                    models.CharField(
                        max_length=150, verbose_name="Type of Water Detector"
                    ),
                ),
                (
                    "monitoring_procedures",
                    models.TextField(blank=True, verbose_name="Monitoring Procedures"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coop.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "ordering": ["text"],
            },
        ),
        migrations.CreateModel(
            name="WaterDetector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Detector Name"),
                ),
                ("location", models.CharField(max_length=50, verbose_name="Location")),
                (
                    "street",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wd_address",
                        to="coop.address",
                    ),
                ),
            ],
        ),
    ]
