# Generated by Django 4.2.7 on 2023-11-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0015_state_waterdetectorcategory_waterdetector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waterdetector",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="waterdetectorcategory",
            options={},
        ),
        migrations.RemoveField(
            model_name="waterdetectorcategory",
            name="location",
        ),
        migrations.AddField(
            model_name="waterdetectorcategory",
            name="water_detector",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="coop.waterdetector",
                verbose_name="Water Detector",
            ),
        ),
    ]
