# Generated by Django 4.2.7 on 2023-11-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0017_name_heatingcompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisasterTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary"),
                            ("Backup 1", "Backup 1"),
                            ("Backup 2", "Backup 2"),
                        ],
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="Phone"),
                ),
                (
                    "contact_cell_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Cell Phone"
                    ),
                ),
                (
                    "contact_after_hours_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="After Hours Phone"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoolingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Organization Name"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city",
                        to="coop.city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
