# Generated by Django 4.2.7 on 2023-11-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0018_disasterteam_coolingsystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Team Name")),
            ],
        ),
        migrations.CreateModel(
            name="TeamResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responsibility",
                    models.IntegerField(
                        choices=[
                            (1, "Disaster Team Leader"),
                            (2, "Administrator/Supplies Coordinator"),
                            (3, "Collections Recovery Specialist"),
                            (4, "Subject Specialist/Department Head"),
                            (5, "Work Crew Coordinator"),
                            (6, "Technology Coordinator"),
                            (7, "Building Recovery Coordinator"),
                            (8, "Security Coordinator"),
                            (9, "Public Relations Coordinator"),
                            (10, "Documentation Coordinator"),
                        ],
                        verbose_name="Responsibility",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_responsibilities",
                        to="coop.name",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_member_responsibilities",
                        to="coop.teamname",
                    ),
                ),
            ],
        ),
    ]
