# Generated by Django 4.2.7 on 2023-11-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0020_disasterresponseteammember_databackup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reconfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_or_contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Title/Contact"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address1"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address2"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=50, verbose_name="Zip"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Phone"),
                ),
                (
                    "cell_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Cell Phone"
                    ),
                ),
                (
                    "pager",
                    models.CharField(blank=True, max_length=15, verbose_name="Pager"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=150, verbose_name="Email"),
                ),
                (
                    "outside_organization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Organization"
                    ),
                ),
                (
                    "staff_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coop.disasterresponseteammember",
                        verbose_name="Staff Person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DataRestoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_or_contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Title/Contact"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address1"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address2"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=50, verbose_name="Zip"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Phone"),
                ),
                (
                    "cell_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Cell Phone"
                    ),
                ),
                (
                    "pager",
                    models.CharField(blank=True, max_length=15, verbose_name="Pager"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=150, verbose_name="Email"),
                ),
                (
                    "outside_organization",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Organization"
                    ),
                ),
                (
                    "staff_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coop.disasterresponseteammember",
                        verbose_name="Staff Person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
