# Generated by Django 4.2.7 on 2023-11-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0022_administrativerecord_computeroperation_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Plan Name")),
                ("description", models.TextField(verbose_name="Plan Description")),
                (
                    "color_code",
                    models.CharField(max_length=20, verbose_name="Color Code"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverallSalvagePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority_ranking",
                    models.PositiveIntegerField(verbose_name="Priority Ranking"),
                ),
                (
                    "material_or_equipment",
                    models.CharField(
                        max_length=150, verbose_name="Material or Equipment"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="Location Floor"),
                ),
            ],
            options={
                "verbose_name_plural": "Overall Salvage Priorities",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority_ranking",
                    models.PositiveIntegerField(verbose_name="Priority Ranking"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Collection Name"),
                ),
                (
                    "location",
                    models.CharField(max_length=300, verbose_name="Location floor"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="coop.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Collections",
            },
        ),
    ]
