# Generated by Django 4.2.7 on 2023-11-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coop", "0024_insuranceinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=50, verbose_name="Policy Number"),
                ),
                (
                    "inception_date",
                    models.DateField(verbose_name="Policy Inception Date"),
                ),
                (
                    "expiration_date",
                    models.DateField(verbose_name="Policy Expiration Date"),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=50,
                        verbose_name="Amount of Business",
                    ),
                ),
                (
                    "deductible",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=50,
                        null=True,
                        verbose_name="Amount of Deductible",
                    ),
                ),
                (
                    "frequency_of_review",
                    models.CharField(
                        max_length=150, verbose_name="Frequency of review"
                    ),
                ),
                (
                    "person_responsible_for_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person responsibily",
                    ),
                ),
            ],
            options={
                "ordering": ["policy_number"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.CharField(max_length=150, verbose_name="Address1")),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Address2"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coop.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "ordering": ["city"],
            },
        ),
    ]
