# Generated by Django 4.2.7 on 2023-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0025_inventories_insurancecompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy1",
                    models.CharField(
                        choices=[
                            ("IC", "Insurance Carrier"),
                            ("IA", "Insurance Agency"),
                        ],
                        max_length=50,
                        verbose_name="Policy Information",
                    ),
                ),
                (
                    "policy2",
                    models.CharField(
                        choices=[
                            ("IC", "Insurance Carrier"),
                            ("IA", "Insurance Agency"),
                        ],
                        max_length=50,
                        verbose_name="Policy Information Business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpensesInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(max_length=50, verbose_name="Policy Number"),
                ),
                (
                    "inception_date",
                    models.DateField(verbose_name="Policy Inception Date"),
                ),
                (
                    "expiration_date",
                    models.DateField(verbose_name="Policy Expiration Date"),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=50,
                        verbose_name="Amount of Extra Expenses Insurance Provided",
                    ),
                ),
                (
                    "deductible",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=50,
                        null=True,
                        verbose_name="Amount of Deductible",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("policy_number", "inception_date", "expiration_date")
                },
            },
        ),
    ]
