# Generated by Django 4.2.7 on 2023-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0026_insurancetype_expensesinsurance"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funds",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=50,
                        verbose_name="Funds Available for Salvage, Repair (in dollars)",
                    ),
                ),
                ("collections", models.TextField(verbose_name="Collections Appraised")),
                (
                    "date_of_last",
                    models.DateField(verbose_name="Date of Last Appraisal"),
                ),
                (
                    "conducting",
                    models.CharField(
                        max_length=150, verbose_name="Person Conducting Appraisal"
                    ),
                ),
                (
                    "responsible",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Person Responsible",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annually", "Annually"),
                        ],
                        max_length=50,
                        verbose_name="Frequency of Evaluation",
                    ),
                ),
                (
                    "procedures",
                    models.TextField(
                        verbose_name="Procedures in Case of Damage or Loss"
                    ),
                ),
                (
                    "documentation",
                    models.TextField(verbose_name="Documentation Required"),
                ),
            ],
        ),
    ]
