# Generated by Django 4.2.7 on 2023-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0027_insurancecoverage"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvacuationProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_or_floor",
                    models.CharField(max_length=150, verbose_name="Area/Floor"),
                ),
                (
                    "person_responsible",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Person Responsible for Clearing Area",
                    ),
                ),
                (
                    "backup_1",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Backup #1",
                    ),
                ),
                (
                    "backup_2",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Backup #2",
                    ),
                ),
                (
                    "evacuation_procedures",
                    models.TextField(verbose_name="Evacuation procedure"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffVisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_or_floor",
                    models.CharField(max_length=300, verbose_name="Area/Floor"),
                ),
                (
                    "person_responsible",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Person Responsible for List",
                    ),
                ),
                (
                    "backup_1",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Backup #1",
                    ),
                ),
                (
                    "backup_2",
                    models.CharField(
                        choices=[
                            ("person_1", "Person 1"),
                            ("person_2", "Person 2"),
                            ("backup_1", "Backup #1"),
                            ("backup_2", "Backup #2"),
                        ],
                        max_length=150,
                        verbose_name="Backup #2",
                    ),
                ),
            ],
        ),
    ]
