# Generated by Django 4.2.7 on 2023-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0028_evacuationprocedure_staffvisitorlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_or_floor",
                    models.CharField(max_length=150, verbose_name="Area/Floor"),
                ),
                (
                    "staff_member_in_charge",
                    models.CharField(max_length=150, verbose_name="Staff Member"),
                ),
                (
                    "backup_1",
                    models.CharField(max_length=150, verbose_name="Backup #1"),
                ),
                (
                    "backup_2",
                    models.CharField(max_length=150, verbose_name="Backup #2"),
                ),
                ("location", models.CharField(max_length=300, verbose_name="Location")),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyCallList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_member",
                    models.CharField(max_length=150, verbose_name="Staff Member"),
                ),
                (
                    "estimated_response_time",
                    models.CharField(
                        max_length=50, verbose_name="Estimated Response Time"
                    ),
                ),
                (
                    "position_on_call_list",
                    models.PositiveIntegerField(verbose_name="Position on Call List"),
                ),
            ],
        ),
    ]
