# Generated by Django 4.2.7 on 2023-11-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0030_collectionstorage_commandcenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DryingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            (
                                "Within Building/Institution",
                                "Within Building/Institution",
                            ),
                            ("Off-Site", "Off-Site"),
                        ],
                        max_length=50,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "space_available",
                    models.CharField(max_length=150, verbose_name="Space Available"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=150, verbose_name="Contact Person"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "cell_phone",
                    models.CharField(max_length=15, verbose_name="Cell Phone"),
                ),
                (
                    "after_hours_phone",
                    models.CharField(max_length=15, verbose_name="After-Hours Phone"),
                ),
                ("pager", models.CharField(max_length=15, verbose_name="Pager")),
            ],
        ),
    ]
