# Generated by Django 4.2.7 on 2023-11-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0031_dryingspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emergency_services",
                    models.CharField(
                        choices=[
                            ("PD", "Police Department"),
                            ("EM", "Emergency Management"),
                            ("LM", "Local Emergency Management"),
                            ("ES", "Emergency Services"),
                        ],
                        max_length=50,
                        verbose_name="Emergency Services",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Organization Name"),
                ),
                ("state", models.CharField(max_length=50, verbose_name="State")),
                (
                    "contact_person",
                    models.CharField(
                        max_length=150,
                        verbose_name="Contact Person within Fire Department",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "cell_phone",
                    models.CharField(max_length=20, verbose_name="Cell Phone"),
                ),
                ("fax", models.CharField(max_length=20, verbose_name="Fax")),
                ("website", models.URLField(max_length=300, verbose_name="Website")),
            ],
            options={
                "ordering": ["name", "state"],
            },
        ),
        migrations.CreateModel(
            name="MaterialsService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Service")),
                (
                    "backup",
                    models.CharField(max_length=50, verbose_name="Backup Liaison"),
                ),
                ("date", models.DateField()),
                (
                    "review_date",
                    models.DateField(
                        verbose_name="Date Review of Collection Priorities"
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        verbose_name="Date of Last Inspection by Fire Marshal"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        max_length=150,
                        verbose_name="Contact Person within Fire Department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="coop.organization",
                    ),
                ),
            ],
        ),
    ]
