# Generated by Django 4.2.7 on 2023-11-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coop", "0032_organization_materialsservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Maintenance",
                    ),
                ),
                (
                    "utilities",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Utilities",
                    ),
                ),
                (
                    "facilities",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Facilities",
                    ),
                ),
                (
                    "janitorial_services",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Janitorial Services",
                    ),
                ),
                (
                    "electrician",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Electrician",
                    ),
                ),
                (
                    "plumber",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("utilities", "Utilities"),
                            ("facilities", "Facilities"),
                            ("janitorial", "Janitorial"),
                            ("electrician", "Electrician"),
                            ("plumber", "Plumber"),
                        ],
                        max_length=50,
                        verbose_name="Plumber",
                    ),
                ),
            ],
            options={
                "ordering": ["maintenance"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("CE", "Computer Emergency"),
                            ("O", "Organization"),
                            ("CA", "Legal Advisor"),
                            ("AB", "Architecture Builder"),
                            ("GC", "Gas Company"),
                            ("OC", "Oil Company"),
                            ("EC", "Electric Company"),
                            ("WUC", "Water Utility Company"),
                            ("ECO", "Elevator Company"),
                        ],
                        max_length=3,
                        verbose_name="Categories",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="materialsservice",
            name="organization",
        ),
    ]
